name: Amax CDN deployment [k8s]

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_IMAGE: ghcr.io/aib0t/amax_cs:prod
  DOCKER_IMAGE_TAG: prod
  HELM_PATH: ./helm/cs-amax-emu
  SERVICE_NAME: cs-amax-emu
  NAMESPACE: amax
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: Aib0t
        password: ${{ secrets.SECRET_GITHUB_TOKEN }} 

    - name: Pull Docker container if exists
      run: docker pull ${{ env.DOCKER_IMAGE }} || true
       
    - name: Build, tag, and push image to registry
      id: build-image
      run: |
          docker build -f Dockerfile -t ${{ env.DOCKER_IMAGE }} .
          docker push ${{ env.DOCKER_IMAGE }}    

    - name: Create kube config
      run: |
        mkdir -p $HOME/.kube/
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
        
    - name: Install helm
      run: |
        curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
        tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
        mv linux-amd64/helm /usr/local/bin/helm
        helm version
        
    - name: Lint helm charts
      run: helm lint ${{ env.HELM_PATH }}
      
    - name: Deploy
      run: |
        helm upgrade --install --atomic --timeout 2m -f ${{ env.HELM_PATH }}/values.yaml ${{ env.SERVICE_NAME }} ${{ env.HELM_PATH }} --set image.tag=${{ env.DOCKER_IMAGE_TAG }} --namespace ${{ env.NAMESPACE }}
